### ISSUE TITLE
Vision based actions

### ISSUE THREAD

**Issue by qwertycloudhub** [Yeti-Robotics/crescendo-java-2024#87]
Use pose to determine what action to take. The same button should be able to:

- [ ] Run shuttle code when in shuttle zone
- [ ] Run shooter code when in shooting zone
- [ ] Run amp code when in amp zone

**Comment by drew-beamer** [comment]
@qwertycloudhub lets break up this ticket into three—although the shuttle code is now done so we might just need shooter/amp?

**Comment by qwertycloudhub** [comment]
well we would still need to code the part where it changes to shuttle when its in that area, so I think 3 parts makes sense

**Comment by drew-beamer** [comment]
Got it. I misinterpreted. Let's split it up and close this issue.
